; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-n16r8v]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

;Configuração para upload de código
upload_port = COM4
upload_speed = 115200

;Configuração arpa monitoramento pela porta serial (Terminal)
monitor_port = COM4
monitor_speed = 115200
;monitor_filters = log2file

; garante que o diretório lib/ será usado
lib_deps = 
    ${PROJECT_LIBDEPS_DIR}
    ${PROJECT_LIB_DIR}

; se quiser adicionar caminhos extras manualmente
lib_extra_dirs = lib

; suporte a ponto flutuante %f, %e e %g no AVG isso consome ~1,5kB
;So pé aplciavel para AVR (quando compialr codigo apra Arduino uno/mega descomente esta linha)
;build_flags = -Wl,-u,vfprintf -lprintf_flt -lm

;Verifique no forum: https://forum.lvgl.io/t/free-and-open-source-eez-studio/12954/54?page=3
[env]
build_flags = 
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -I ./include
    -I ./lib
    -I src
    -fpermissive
